NAME ?= opensips
OPENSIPS_VERSION ?= 3.0
OPENSIPS_BUILD ?= nightly
OPENSIPS_DOCKER_TAG ?= dave
OPENSIPS_CLI ?= true
OPENSIPS_JSON_MODULE ?= false
OPENSIPS_MYSQL_MODULE ?= true
OPENSIPS_HTTP_MODULE ?= true
OPENSIPS_DIALPLAN_MODULE ?= false

all: build start

.PHONY: build start
build:
	docker build \
		--build-arg=OPENSIPS_BUILD=$(OPENSIPS_BUILD) \
		--build-arg=OPENSIPS_VERSION=$(OPENSIPS_VERSION) \
		--build-arg=OPENSIPS_CLI=${OPENSIPS_CLI} \
		--build-arg=OPENSIPS_JSON_MODULE=${OPENSIPS_JSON_MODULE} \
		--build-arg=OPENSIPS_MYSQL_MODULE=${OPENSIPS_MYSQL_MODULE} \
		--build-arg=OPENSIPS_HTTP_MODULE=${OPENSIPS_HTTP_MODULE} \
		--build-arg=OPENSIPS_DIALPLAN_MODULE=${OPENSIPS_DIALPLAN_MODULE} \
		--tag="opensips:$(OPENSIPS_DOCKER_TAG)" \
		.

start:
	docker run -d --name $(NAME) -p 5060:5060/udp opensips:$(OPENSIPS_DOCKER_TAG)
